/********************************************************************
* EightPiUnpackerDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EightPiUnpackerDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEightPiUnpackerDictionary();
extern void G__cpp_setup_inheritanceEightPiUnpackerDictionary();
extern void G__cpp_setup_typetableEightPiUnpackerDictionary();
extern void G__cpp_setup_memvarEightPiUnpackerDictionary();
extern void G__cpp_setup_globalEightPiUnpackerDictionary();
extern void G__cpp_setup_memfuncEightPiUnpackerDictionary();
extern void G__cpp_setup_funcEightPiUnpackerDictionary();
extern void G__set_cpp_environmentEightPiUnpackerDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Event.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_TClass;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_TBuffer;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_TObject;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_maplEunsignedsPcharcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEunsignedsPchargRcOallocatorlEpairlEconstsPunsignedsPcharcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_pairlEunsignedsPshortcOunsignedsPshortgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_vectorlEpairlEunsignedsPshortcOunsignedsPshortgRcOallocatorlEpairlEunsignedsPshortcOunsignedsPshortgRsPgRsPgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_reverse_iteratorlEvectorlEpairlEunsignedsPshortcOunsignedsPshortgRcOallocatorlEpairlEunsignedsPshortcOunsignedsPshortgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_maplEunsignedsPcharcOvectorlEpairlEunsignedsPshortcOunsignedsPshortgRcOallocatorlEpairlEunsignedsPshortcOunsignedsPshortgRsPgRsPgRcOlesslEunsignedsPchargRcOallocatorlEpairlEconstsPunsignedsPcharcOvectorlEpairlEunsignedsPshortcOunsignedsPshortgRcOallocatorlEpairlEunsignedsPshortcOunsignedsPshortgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_maplEunsignedsPcharcOunsignedsPlongcOlesslEunsignedsPchargRcOallocatorlEpairlEconstsPunsignedsPcharcOunsignedsPlonggRsPgRsPgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_Ulm;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_Detector;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_Event;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EightPiUnpackerDictionaryLN_maplEunsignedsPcharcOintcOlesslEunsignedsPchargRcOallocatorlEpairlEconstsPunsignedsPcharcOintgRsPgRsPgR;

/* STUB derived class for protected member access */
typedef vector<Detector,allocator<Detector> > G__vectorlEDetectorcOallocatorlEDetectorgRsPgR;
